version: '3.7'

services:
  # Backend API
  smart-brain-api:
    container_name: backend
#    image: node: 8.10.0
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment:
      POSTGRES_URI: postgres://sally:secret@postgres:5432/smartbraindocker
    links:
      - postgres
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/smart-brain-api

    # Postgres
  postgres:
    environment:
      POSTGRES_USER: sally
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smartbraindocker
      POSTGRES_HOST: postgres
    image: postgres
    ports:
      - "5432:5432"